#!/bin/bash

trap 'echo "ERROR: $BASH_SOURCE: line $LINENO" >&2' ERR
set -o errexit -o errtrace -o pipefail
#set -o xtrace -o verbose

if [ "$1" == "-v" ]; then
  verboseout=1
  shift
fi
BASEDIR=`cd ${0%/*}; pwd`

. $BASEDIR/../.env
. $TOPDIR/lib.sh
cd $TEST_REPO

DISTRIBUTION_NAME=distribution_test

# Note: It's easier to do this now than when the checkout is all cluttered
out Test creating a release
make dist
unzip -l ../$DISTRIBUTION_NAME-0.1.0.zip | grep .asc | awk '{print $4}'
# grep exits with 1 if it can't find anything
out "Ensure there's at least some docs in the distribution" # This is mostly to make sure the next test works
unzip -l ../$DISTRIBUTION_NAME-0.1.0.zip | egrep -q 'asc|adoc|asciidoc|html|md|txt' || exit 1
out Ensure there are no pgxntool docs in the distribution
if unzip -l ../$DISTRIBUTION_NAME-0.1.0.zip | grep pgxntool/ | egrep 'asc|adoc|asciidoc|html|md|txt'; then
  die 5 "Found document files in pgxntool/"
fi

check_log

# vi: expandtab sw=2 ts=2
