#!/bin/bash

trap 'echo "ERROR: $BASH_SOURCE: line $LINENO" >&2' ERR
set -o errexit -o errtrace -o pipefail
#set -o xtrace -o verbose

if [ "$1" == "-v" ]; then
  verboseout=1
  shift
fi
BASEDIR=`cd ${0%/*}; pwd`

. $BASEDIR/../.env
. $TOPDIR/lib.sh
cd $TEST_REPO

out Make certain test/output gets created
[ ! -e $TEST_REPO/test/output ] || (out "ERROR! test/output directory should not exist!"; exit 1)
make test # TODO: ensure this exits non-zero
[ -e $TEST_REPO/test/output ] || (out "ERROR! test/output directory does not exist!"; exit 1)
[ -d $TEST_REPO/test/output ] || (out "ERROR! test/output is not a directory!"; exit 1)

out And copy expected output file to output dir that should now exist
cp $TOPDIR/pgxntool-test.source test/output

out Run make test again
make test || exit 1
out -v ^^^ Should be clean output ^^^

out Remove input and output directories, make sure output is not recreated
rm -rf $TEST_REPO/test/input $TEST_REPO/test/output
make test
[ ! -e $TEST_REPO/test/output ] || (out "ERROR! test/output directory exists!"; exit 1)

check_log

# vi: expandtab sw=2 ts=2
